package org.andy.work.entity;
// Generated 2016-7-21 12:01:12 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * AcctAuthority generated by hbm2java
 */
@Entity
@Table(name = "acct_authority", catalog = "test")
public class AcctAuthority implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4450885715016140998L;
	private String id;
	private String name;
	private Set<AcctRole> acctRoles = new HashSet<AcctRole>(0);
	//Spring-Security默认角色/授权名前缀
	private static final String AUTHORITY_PREFIX = "ROLE_";

	public AcctAuthority() {
	}

	public AcctAuthority(String id) {
		this.id = id;
	}

	public AcctAuthority(String id, String name, Set<AcctRole> acctRoles) {
		this.id = id;
		this.name = name;
		this.acctRoles = acctRoles;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "acct_role_authority", catalog = "test", joinColumns = {
			@JoinColumn(name = "authority_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "role_id", nullable = false, updatable = false) })
	public Set<AcctRole> getAcctRoles() {
		return this.acctRoles;
	}

	public void setAcctRoles(Set<AcctRole> acctRoles) {
		this.acctRoles = acctRoles;
	}

	@Transient
	public String getPrefixedName(){
		return AUTHORITY_PREFIX + this.name;
	}
}
