package org.andy.work.entity;
// Generated 2016-7-21 11:42:26 by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcctUserRole generated by hbm2java
 */
@Entity
@Table(name = "acct_user_role", catalog = "test")
public class AcctUserRole implements java.io.Serializable {

	private AcctUserRoleId id;
	private AcctUser acctUser;
	private AcctRole acctRole;

	public AcctUserRole() {
	}

	public AcctUserRole(AcctUserRoleId id, AcctUser acctUser, AcctRole acctRole) {
		this.id = id;
		this.acctUser = acctUser;
		this.acctRole = acctRole;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false, length = 36)),
			@AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false, length = 36)) })
	public AcctUserRoleId getId() {
		return this.id;
	}

	public void setId(AcctUserRoleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public AcctUser getAcctUser() {
		return this.acctUser;
	}

	public void setAcctUser(AcctUser acctUser) {
		this.acctUser = acctUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false, insertable = false, updatable = false)
	public AcctRole getAcctRole() {
		return this.acctRole;
	}

	public void setAcctRole(AcctRole acctRole) {
		this.acctRole = acctRole;
	}

}
