package org.andy.work.entity;
// Generated 2016-7-21 11:42:26 by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcctRoleAuthority generated by hbm2java
 */
@Entity
@Table(name = "acct_role_authority", catalog = "test")
public class AcctRoleAuthority implements java.io.Serializable {

	private AcctRoleAuthorityId id;
	private AcctAuthority acctAuthority;
	private AcctRole acctRole;

	public AcctRoleAuthority() {
	}

	public AcctRoleAuthority(AcctRoleAuthorityId id, AcctAuthority acctAuthority, AcctRole acctRole) {
		this.id = id;
		this.acctAuthority = acctAuthority;
		this.acctRole = acctRole;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false, length = 36)),
			@AttributeOverride(name = "authorityId", column = @Column(name = "authority_id", nullable = false, length = 36)) })
	public AcctRoleAuthorityId getId() {
		return this.id;
	}

	public void setId(AcctRoleAuthorityId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "authority_id", nullable = false, insertable = false, updatable = false)
	public AcctAuthority getAcctAuthority() {
		return this.acctAuthority;
	}

	public void setAcctAuthority(AcctAuthority acctAuthority) {
		this.acctAuthority = acctAuthority;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false, insertable = false, updatable = false)
	public AcctRole getAcctRole() {
		return this.acctRole;
	}

	public void setAcctRole(AcctRole acctRole) {
		this.acctRole = acctRole;
	}

}
